// src/app/components/explore-all-tools/category-nav/category-nav.component.ts
import { Component, EventEmitter, Input, Output, ViewChild, ElementRef, AfterViewChecked } from '@angular/core';
import { CommonModule } from '@angular/common';
import { categoriesData } from '../../../data/categories';
import { ICONS } from '../../../data/icons';
import { SafeHtmlPipe } from '../../../pipes/safe-html.pipe';

@Component({
  selector: 'app-category-nav',
  standalone: true,
  imports: [CommonModule, SafeHtmlPipe],
  templateUrl: './category-nav.component.html',
  styleUrl: './category-nav.component.css'
})
export class CategoryNavComponent implements AfterViewChecked {
  getIconData(name: string) {
    return ICONS[name] || ICONS['file'];
  }
  @Input() selectedCategoryId: string = 'all';
  @Output() selectCategory = new EventEmitter<string>();
  @ViewChild('scrollContainer') scrollContainer!: ElementRef;

  categories = [
    { id: 'all', name: 'All Tools', icon: 'layers' },
    ...categoriesData
  ];

  ngAfterViewChecked() {
    const activeItem = this.scrollContainer.nativeElement.querySelector('[data-active="true"]');
    if (activeItem) {
      // Logic for smooth scroll could go here
    }
  }

  onSelectCategory(id: string) {
    this.selectCategory.emit(id);
  }

  getIcon(icon: string): string {
    if (icon === 'all') return 'layers';
    if (icon === 'minimize') return 'minimize-2';
    return icon;
  }
}

<div class="w-full border-b border-main bg-opacity-85 backdrop-blur-sm sticky top-16 z-30 mb-8" style="background-color: var(--glass-bg); border-color: var(--border-main);">
  <div
    #scrollContainer
    class="w-full flex items-center justify-center gap-2 overflow-x-auto no-scrollbar py-4 px-6"
    >
    @for (cat of categories; track cat) {
      <button
        (click)="onSelectCategory(cat.id)"
        [attr.data-active]="selectedCategoryId === cat.id"
        class="flex items-center gap-2 px-4 py-2 rounded-full whitespace-nowrap transition-all duration-300 font-bold text-sm border-2"
      [ngClass]="selectedCategoryId === cat.id 
        ? 'bg-gradient-to-r from-indigo-600 to-violet-600 border-indigo-600 text-white shadow-md shadow-indigo-500/20 scale-105' 
        : 'bg-card border-main text-muted hover:border-indigo-400 hover:text-indigo-600 dark:hover:border-indigo-500 dark:hover:text-indigo-400'"
        [style]="selectedCategoryId !== cat.id ? 'background-color: var(--bg-card); border-color: var(--border-main); color: var(--text-muted);' : ''"
        >
        <svg [attr.class]="'w-4 h-4 ' + (selectedCategoryId === cat.id ? 'text-white' : 'text-current')" [attr.viewBox]="getIconData(getIcon(cat.icon)).viewBox" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" [innerHTML]="getIconData(getIcon(cat.icon)).path | safeHtml"></svg>
        {{ cat.name }}
      </button>
    }
  </div>
</div>

// src/components/CategoryNav.tsx
import React, { useRef, useEffect } from 'react';
import { categoriesData, type Category } from '../data/categories';
import { 
  FileTextIcon, 
  MinimizeIcon, 
  FileUpIcon, 
  DownloadIcon, 
  PenToolIcon, 
  LockIcon,
  LayersIcon
} from './Icons';

interface CategoryNavProps {
  selectedCategoryId: string;
  onSelectCategory: (id: string) => void;
}

const iconMap: Record<string, React.FC<{ className?: string }>> = {
  'file-text': FileTextIcon,
  'minimize': MinimizeIcon,
  'file-up': FileUpIcon,
  'download': DownloadIcon,
  'pen-tool': PenToolIcon,
  'lock': LockIcon,
  'all': LayersIcon
};

export const CategoryNav: React.FC<CategoryNavProps> = ({ selectedCategoryId, onSelectCategory }) => {
  const scrollRef = useRef<HTMLDivElement>(null);

  // Auto-scroll selected item into view on mobile
  useEffect(() => {
    const activeItem = scrollRef.current?.querySelector('[data-active="true"]');
    if (activeItem) {
      activeItem.scrollIntoView({ behavior: 'smooth', block: 'nearest', inline: 'center' });
    }
  }, [selectedCategoryId]);

  const categories = [
    { id: 'all', name: 'All Tools', icon: 'all' },
    ...categoriesData
  ];

  return (
    <div className="w-full border-b border-slate-200 dark:border-slate-800 bg-white/50 dark:bg-slate-950/50 backdrop-blur-sm sticky top-16 z-30 mb-8">
      <div 
        ref={scrollRef}
        className="w-full flex items-center justify-center gap-2 overflow-x-auto no-scrollbar py-4 px-6"
      >
        {categories.map((cat) => {
          const Icon = iconMap[cat.icon] || FileTextIcon;
          const isActive = selectedCategoryId === cat.id;
          
          return (
            <button
              key={cat.id}
              onClick={() => onSelectCategory(cat.id)}
              data-active={isActive}
              className={`
                flex items-center gap-2 px-4 py-2 rounded-full whitespace-nowrap transition-all duration-300 font-bold text-sm border-2
                ${isActive 
                  ? 'bg-indigo-600 border-indigo-600 text-white shadow-md scale-105' 
                  : 'bg-white dark:bg-slate-900 border-slate-200 dark:border-slate-800 text-slate-600 dark:text-slate-400 hover:border-indigo-400 dark:hover:border-indigo-600 hover:text-indigo-600 dark:hover:text-indigo-400'
                }
              `}
            >
              <Icon className={`w-4 h-4 ${isActive ? 'text-white' : 'text-current'}`} />
              {cat.name}
            </button>
          );
        })}
      </div>
    </div>
  );
};
